### ISSUE TITLE
List of upcoming events

### ISSUE THREAD

**Issue by RobertJLewis** [RobertJLewis/project-planning--demo-#1]
**User story**
As a local resident, I want to see a lust of upcoming community events

**Acceptance Criteria**

- [ ] The homepage display a list of upcoming community everts.
- [ ] Each event liting includes the even name, date, time, and a brief description.
- [ ] The list is responsive and looks good on all main device sires

**Tasks**

- [ ] Add an HTML section on the homepage dedicated to upcoming community events
- [ ] Style the event, Int using Bootstrap
- [ ] Add some sample events including event name, date, time and brief description
